export const COPY_ICON = '/assets/icons/copyIcon.svg'
export const PASTE_ICON = '/assets/icons/pasteIcon.svg'
export const SUN = '/assets/icons/sun.svg'
export const MOON = '/assets/icons/moon.svg'
export const LIKE = '/assets/icons/like.svg'
export const SHARE = '/assets/icons/share.svg'
export const COMMENT = '/assets/icons/comment.svg'
